run-dist: #запуск исполняемого файла
	./build/install/app/bin/app
run-checkstyle:
	./gradlew checkstyleMain

install:
	./gradlew clean
	./gradlew installDist

build:
	./gradlew build


.PHONY: build